<?php
	require_once("common.php");
	if(!isset($_POST['username'])||trim($_POST['username'])==""){
		//header("Location: resetPassword.php?error=incomplete");
		errorMessage("Please fill in the field", "resetPassword.php");
		die();
	}
	require_once("connect.php");
	$query=mysql_query("SELECT * FROM user WHERE email='".mysql_real_escape_string($_POST['username'])."'") or die();
	if(mysql_num_rows($query)==0){
		errorMessage("User does not exist!", "resetPassword.php");
		die();
	}
	$user = mysql_real_escape_string($_POST['username']);
	$reset_code = str_shuffle(sha1(time()));
	$newpass = substr($reset_code,5,8);
	$query = mysql_query("UPDATE `user` SET `reset_code`='$reset_code' WHERE email='$user'") or die(mysql_error());
	$headers = "From: devs@journy.wehavenodomain.com";
	$message= 
	"Hello, \r\n \r\n
We received a password reset request from your account. If this was not you, do take the 
liberty to ignore this email. If it was, please follow this link to reset your password: 
http://54.187.179.115/reset.php?code=$reset_code \r\n \r\n
Do note that your password will be reset to $newpass which is a secure password generated by our servers. Nonetheless, 
set your password to something you will remember the next time you log in. \r\n \r\n
Best Regards, \r\n
Guan's Guys (The Journy Team)";
	mail($user,"Journy Password Reset",$message,$headers);
	//header("Location: index.php?message=resetrequest");
	infoMessage("Reset instructions have been emailed to you", "index.php");
?>